language: go
before_install:
  - go get -u golang.org/x/oauth2
  - go get -u github.com/google/go-github/github
  - go get -u gopkg.in/yaml.v2
  - go get -u github.com/stretchr/testify/assert
install: 
  - go run main.go utils.go 
after_success:
  - 'git commit -am "Travis build: $TRAVIS_BUILD_NUMBER"'
  - git remote add github https://$GITHUB_TOKEN@github.com/jungju/awesome-check.git
  - git push --quiet --set-upstream github master
